### ISSUE TITLE
Different coloured lists

### ISSUE THREAD

**Issue by kufton** [talpor/django-dashing#67]
Is it possible to create different coloured widgets without having to create a new custom widget each time?
Another way of wording this might be, is it possible to edit the style/class of a widget when you're adding it to a dashboard. Similar to the color option, but that only impacts the background, not the div holding the data displayed on top of it.

**Comment by individuo7** [comment]
No, currently it is not posible to modify the style or class of a widget when is being adding (only the `background-color` using the **color** option)
You can use the selector `:nth-child` of css in order to give specifics styles to a widget because they are always added in the same order, for example `.widget-number:nth-child(2) {font-size: 2em}` is not the ideal but is a workaround for this requirement.
